-- ============================================
-- SCRIPT DE INSERCIÓN DE MATERIAS - SECUNDARIA
-- I.E. N° 16793 "EULALIO VILLEGAS RAMOS"
-- ============================================

-- Insertar materias de SECUNDARIA
INSERT INTO materias (nombre, created_at, updated_at)
VALUES
    ('COMUNICACIÓN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MATEMATICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CIENCIAS SOCIALES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('DESARROLLO PERSONAL, CUIDADANIA Y CIVICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TUTORIA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ARTE Y CULTURA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EDUCACION RELIGIOSA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CIENCIA Y TECNOLOGIA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EDUCACION PARA EL TRABAJO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('INGLES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EDUCACION FISICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (nombre) DO NOTHING;

-- Verificar que se insertaron correctamente
SELECT 
    id,
    nombre,
    created_at,
    updated_at
FROM materias 
WHERE deleted_at IS NULL
ORDER BY nombre;

-- Contar materias insertadas
SELECT COUNT(*) as total_materias
FROM materias 
WHERE deleted_at IS NULL;
